### ISSUE TITLE
nzbbuffer.js error

### ISSUE THREAD

**Issue by usenethound** [animetosho/Nyuu#1]
Things have been working great for about a week using Nyuu but today I hit this error posting to the Blocknews EU server.

While reading files (which it never totally finishes before timing out) I get
NNTP connection error occurred: Response timed out (3 or 4 of these errors) then
NNTPError: Response timed out
/root/bin/Nyuu/lib/nzbbuffer.js:51
if(!this.segments) throw new Error('Already finished');
............................^

Error: Already finished
at Object.NZBFile.set (/root/bin/Nyuu/lib/nzbbuffer.js:51:28)
at Object.UploadManager.onPosted (/root/bin/Nyuu/lib/uploadmgr.js:173:9)
at Object.Uploader._postComplete (/root/bin/Nyuu/lib/uploader.js:288:24)
at /root/bin/Nyuu/lib/uploader.js:271:9
at /root/bin/Nyuu/lib/nntp.js:409:9
at Object. (/root/bin/Nyuu/lib/nntp.js:476:8)
at _respFunc (/root/bin/Nyuu/lib/nntp.js:494:7)
at Object.NNTP._onData (/root/bin/Nyuu/lib/nntp.js:309:6)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)

I proceeded to try posting the same file about 3 or 4 times with the same result. I then switched to newsmangler and the file posted without issue. The file in question is a larger file than what I might usually post at 3.14GB

**Comment by animetosho** [comment]
Thanks for reporting the issue!

I don't know the reason for why you're getting timeout errors. You can try to force it through via the `--skip-errors post-timeout` CLI flag, but you may get missing posts. If you think that the server is just slow to respond, you can also try increasing the timeout via the `--timeout` flag (note, v0.2.4 has a bug and interprets this value in miliseconds - if you're using that version, specify `--timeout 120000` to set the timeout to 2 minutes, if you're using my latest code, specify `--timeout 120s` or `--timeout 2m` instead)

I tested Newsmangler against a server which doesn't send a reply. It looks like it just sits there waiting indefinitely. A real server would likely close the connection for inactivity, and then Newsmangler would attempt to re-connect, but there doesn't appear to be any limit to retry attempts.  
So it looks like Newsmangler isn't getting response timeouts from the server. Either the server is slow to respond, or Nyuu is posting in a way that the server wants to ignore :/

**Comment by usenethound** [comment]
Thanks animetosho, I pulled the latest code from this morning and added `--time 120s` to my command line and reposted that same file. I got to 99.92% completion  before I got the `NNTPError: Response timed out`

All file(s) read...
NNTP connection error occurred: Response timed out
NNTP connection error occurred: Response timed out
NNTP connection error occurred: Response timed out
NNTP connection error occurred: Response timed out
NNTP connection error occurred: Response timed out
NNTP connection error occurred: Response timed out
NNTP connection error occurred: Response timed out
NNTP connection error occurred: Response timed out
NNTP connection error occurred: Response timed out
NNTPError: Response timed out

The resulting post had 4 files missing parts, all of which were 98.6% complete. I'm using the nzbcheck function but it doesn't seem to be able to get past this error to try and repost the missing parts before timing out. Is this just a Blocknews issue or could there be more going on? 

Thanks!

**Comment by animetosho** [comment]
The 'Response timed out' error refers to when the server doesn't return a response.  
Basically, Nyuu sends requests to the target server (such as, 'post this') and the server needs to then send back a response (such as 'post was OK', or maybe 'post failed'). That's what happens if everything is working correctly.  
In reality, all sorts of issues can crop up, and to deal with one in particular, Nyuu will limit the amount of time it waits for the server to respond (by default, up to 60 seconds). If no response is received within this time, Nyuu will print a warning, tear down the connection, reconnect and then re-send the failed message. This cycle is repeated until it either succeeds, or the max retry attempts is reached, after which, Nyuu just gives up, throws an error and exits (unless you tell it to skip errors, in which case, the failure is ignored and it continues on).

Interestingly, I've actually noticed this happen before. I've always thought it to be a server quirk, perhaps due to filtering or similar, as it always seems to target one particular segment in a file. I have also seen another poster get the same issue at times (they're using Newsmangler).  
Since you're reporting the same issue, and the fact that Newsmangler seems to work fine, I wonder if there's something more to this. I've just added a flag `--dump-failed-posts` which may help if you're interested in seeing exactly which post(s) are failing (supply something like `--dump-failed-posts .` to dump failed posts to the current directory). Perhaps it may help with identifying a failure pattern? I don't know.

So really, I can't say exactly what the problem is. I'd say it's very likely a server problem, but if another usenet poster can succeed, perhaps I need to code in a workaround (I already have a few in place). I may try looking into it more, but if you willing to experiment, things you can try:

* changing subject name (or renaming your files)
* reduce the article size (like `-a 625K`)
* try a different server by the same provider (US/EU2)

**Comment by usenethound** [comment]
Thanks for the feedback. You nailed the issue right on the head

> as it always seems to target one particular segment (usually the first or last) in each file of a group

That's exactly what's happening with it being the last segment in this case. As far as you recommendations for things to try, I have tried both of these.
1. changing subject name (or renaming your files)
2. try a different server by the same provider (US/EU2)

I will try changing the article size today and also add in the `--dump-failed-posts` switch

Thanks a bunch!

**Comment by usenethound** [comment]
To get around this issue for now I just added `--skip-errors post-timeout` to my command line as there are always articles in this particular file when rar'd that Blocknews fails to accept. I went back and checked the newsmangler post of the same rar'd file and although it didn't throw any errors, there were indeed 3 or 4 missing articles.

**Comment by animetosho** [comment]
Thanks for trying those out and getting back to me. I presume none of those made any difference at all?

It makes more sense if Newsmangler failed as well. I do wonder what makes the server reject the post still...

I've managed to capture an instance of a post timeout, but this wasn't the first or final piece of the file. After investigation, it seems that making the post smaller improved its chance of success, so I'll be lowering the default article size to improve reliability.  
Shouldn't help your case though, since the final piece is usually smaller than the rest. I'll see if I ever get a case of posts timing out on the final piece.

**Comment by usenethound** [comment]
Yes dropping the article size to 384000 fixed the issue with this file but it also effected upload speeds a bit. I'm not 100% sure it's the last article of the file getting dropped. How would I go about checking this? I have a feeling it's just a random article like you are seeing.

Thanks again

**Comment by animetosho** [comment]
Ah, thanks for confirming that!

But 325K? That's rather small... I presume you haven't tried various sizes in-between? I've changed the default from 750K to 700K, which I'm hoping works.

**Comment by usenethound** [comment]
Yes it is indeed too small, I will change the article size to 700K and keep you posted

**Comment by animetosho** [comment]
Thanks for that!
