### ISSUE TITLE
Same Yenc Header Name with {rand(N)}

### ISSUE THREAD

**Issue by Antidote2151** [animetosho/Nyuu#132]
Hello,

I noticed that if you enter "{rand(64)}" in the --yenc-name attribute for a command, the name is random, but the name is the same for every article and not different for every article.

Is that how it should be? 
If so, is it possible to include the option that the name is random for each article?

Regards

**Comment by animetosho** [comment]
Yes, that is correct. The name is generated for the file and applied to all articles of that file.

I have no intention of changing this behaviour unless you can convince me otherwise.  
You might be able to find some Nyuu forks that implement what you want however.

**Comment by Antidote2151** [comment]
Well, it would be interesting if the articles were really completely obfuscated, which would save us the complete rar with password protection, for example. This way we can also follow your post where you have already described this nicely and it would probably be an incentive for more people not to do this anymore, because it is then simply really very difficult to get to the files without the NZB.

**Comment by animetosho** [comment]
> it is then simply really very difficult to get to the files without the NZB.

1. Why does this matter?
2. Do you have any evidence/proof for or against this, or is this purely wild speculation?
3. Was it already very difficult to get to the files without any of this?

**Comment by Tensai75** [comment]
Antidote2151 is right.
The Easynews index does analyse the yenc header in the body and articles with the same name in the yenc header are indeed indexed. So the Easynews search will provide results and an NZB file which will enable you to download the whole file if you know what string to search for.
You can argue that no one will know the name string, but a 100% obfuscation should make it impossible for the indexer to connect the individual articles together at all. And to achieve this, all 3 key information strings, subject, from and the name string in the yenc header must be randomized for *every* article in order to cut any connection between the articles.

Regards, Tensai

**Comment by Tensai75** [comment]
> If no one knows the name string, why does it matter if the indexer connected the individual articles?

Because there is a risk that someone who does not have the original NZB file could, in the worst case, download the file, e.g. by simply searching the (newly) indexed uploads in the Easynews search, even though they do not know what they are downloading.

> why do you think they will not just simply resort to other techniques (e.g. using other fields of the yEnc header)?

It is certainly possible that indexer can make use of the other yenc header fileds in order to index the uploads but currently it doesn't seem to be the case. This however can change and we will then need to adapt the obfuscation method probably once again.

> Naming everything 'file' would surely be less identifying, no?

The obfuscation should prevent the upload from appearing in the indexer at all. Naming everything the same would contradict this, although the resulting NZB file would probably be useless.


Ultimately, it's probably a question of how much paranoia you have. But as I said, in my opinion, obfuscation should always aim to prevent uploads from appearing in the indexer at all. And as the indexer evolves, so must the obfuscation method.

**Comment by animetosho** [comment]
> even though they do not know what they are downloading.

How often do people download something they don't know the contents of?

> The obfuscation should prevent the upload from appearing in the indexer at all.

Why?

> Naming everything the same would contradict this

Does it?  
If all uploads have the same name, the indexer can no longer use the name as a reliable means of joining articles together. Perhaps this indexer displays multiple entries for 'file', but whether the articles even match up is a different matter.

> Ultimately, it's probably a question of how much paranoia you have

Unfortunately I don't really believe in unfounded paranoia, as you can probably tell from my responses.  
(hence my general stance against many obfuscation practices)

> And as the indexer evolves, so must the obfuscation method.

I also have no interest in participating in this sort of contest.

**Comment by Tensai75** [comment]
> I also have no interest in participating in this sort of contest.

But you could at least give the option to the users who want to be that paranoid. A new cmd switch and a few lines of code. Shouldn't be that hard to implement... 
Would you accept a PR to implement this?

Regards, Tenasi

**Comment by Tensai75** [comment]
Sure, no problem. I am working on my own, new _"crazy idea"_ of usenet upload anyway ;-)
In any case I very much appreciate your work, thanks mate!

Regards, Tensai

**Comment by animetosho** [comment]
I wish you the best of luck with your endeavor!

**Comment by Antidote2151** [comment]
Thank you for the discussion!
