### ISSUE TITLE
Separate posting/checking server question

### ISSUE THREAD

**Issue by duhagppn** [animetosho/Nyuu#137]
Is there anything stopping Nyuu from reliably posting on one server and (mostly) checking on another using the existing config.js features? 

for example - 
**SERVER1**
postConnections: 29 
checkConnections: 1 

**SERVER2**
postConnections 0 
checkConnections 10

the config.js notes that "servers are currently selected randomly for posting/checking; Nyuu won't otherwise do anything special if you specify multiple servers (this includes falling over if a server is misbehaving)".

Nyuu posts to SERVER1
Nyuu requests post-check
Post-check sent to SERVER2 as it has more available checkers
SERVER2 doesn't find post

would Nyuu then loop back to SERVER1 to re-post as SERVER2 has no post connections available? or would it try to post to SERVER2 and error out?

**Comment by animetosho** [comment]
Sorry, I don't really understand your suggestion. Can you elaborate?

**Comment by duhagppn** [comment]
Apologies, perhaps I've misunderstood the help text. 

> If SERVER1 has 0 check connections, it would _only_ check on SERVER2.

according to the help text if there are 0 check connections then post checking is disabled ("(default 0). Set to 1 to enable checking"). 

to me that reads as "0 = post checking is disabled, don't perform any post checks" and not "post checking is disabled for this server, but can be delegated to servers with available check-connections". 

if the latter is the case then there's no need for my suggestion :-)

**Comment by animetosho** [comment]
Ah I see where you're coming from.

Yes, a value of 0 disables post checking, so if SERVER1 has 0 check connections, post checking is disabled on SERVER1. But since SERVER2 has more than 0 check connections, post checking is *enabled* on SERVER2.

Note that the help applies to the *command line interface*. If you set 0 connections there, it'll set that for all configured servers, which will disable post checking.
