### ISSUE TITLE
Does nyuu not generating nzbs based on file/folder name as *.nzb

### ISSUE THREAD

**Issue by scriptzteam** [animetosho/Nyuu#15]
Does nyuu not generating nzbs based on file/folder name as *.nzb

I see in config.js 
`writeTo: null, // supply a writable stream (or function which returns one) or filename for NZB output`

So is there any function which will return the *.nzb based by filename or directory name?

Thx!

**Comment by animetosho** [comment]
I presume by "file/folder name", you're referring to *input* files/folders?  
If so, which file/directory name are you referring to though? You can supply multiple files/directories to Nyuu, for a single NZB.

If you're looking to create multiple NZBs which are based off the names of a bunch of directories, note that Nyuu never creates more than one NZB per run, so you'll need to run it multiple times to do that. [Here's an example Windows script](https://www.reddit.com/r/usenet/comments/5oktpo/i_need_some_help_with_nyuu_uploader/dcktdf1/) which may be similar, if it's what you're asking for.

**Comment by scriptzteam** [comment]
Ah so likely in ubuntu i need bash script with `for dir in blah blah ...`, easy not a problem at all thx. I thought that nyuu will generate nzb file as upload ends, but nvm simple bash will do :)

**Comment by animetosho** [comment]
Oh I see. Yes, you'll need a shell script for that. Nyuu would otherwise combine both directories into a single NZB.

**Comment by scriptzteam** [comment]
Just did it with shell :D eazy peazy as that :D Also can i ask why nyuu do this - "as uploading it writing to nzb file" can it be rather that after successful upload it will save nzb file?

**Comment by animetosho** [comment]
As for why, in theory, streaming writes can mean less memory consumption for very large jobs, as you don't need to hold the whole XML file in memory. In reality, I suppose it doesn't matter, and considering the overhead of JS, probably doesn't even have a noticeable impact.  
Another benefit is that if the process breaks/crashes, you can still get some output if you intend to recover from it.

Otherwise, I'd think it'd largely be the same? It also does somewhat depend on what you consider to be an unsuccessful upload (Nyuu stopping half way due to an error? Nyuu completing, but with errors?). If you're using a script, one thing you can do is just check the exit code, as Nyuu returns a non-0 exit code if it encountered any major problem, and just unlink the NZB if that happens.

I do suppose adding some sort of option may be useful though, but I'll need to think about it - thanks for pointing it out!

**Comment by scriptzteam** [comment]
For example if i do generating nzbs, those nzbs are being moved to specific directory, but when moving what if still nzb is being writed to nzb file, i do use crontab so i will wont know what nzb files are still being writed, i will move uncomplete nzb then with crontab probably as nyuu still writing as uploading, so thats why, should be atleast a option, anyway good job on nyuu ;)

**Comment by animetosho** [comment]
Oh I see, what about just specifying a different output file and renaming it after completion? e.g.

	nyuu [options] -o something.tmp
	mv something.tmp something.nzb

And then your cron script just moves *.nzb files?

**Comment by scriptzteam** [comment]
but then i still be renaming *.tmp file even its uploading thats not and option, i moving while nyuu uploading

**Comment by animetosho** [comment]
No, the above (shell script portion) should rename the .tmp file only *after* Nyuu is complete.

I'm otherwise not too sure what you mean.

**Comment by scriptzteam** [comment]
I am just uploading with nyuu, but as my cron run, it will move all nzb files into different folder, but it also moves the uncomplete (still being writed) nzb (probably one still being writed but so...)

Is there any way so you can add a something like post processing for custom shell script after nyuu says "[INFO] Finished uploading...." it will run for example my_shell_script.sh with custom commands.

Thx!

**Comment by animetosho** [comment]
I must be missing something because a shell script does exactly that - run commands one after the other.

The following will move the complete NZB to your destination (you don't even need a cron for that) only if no errors are encountered in the run. If you don't care about errors, replace `&&` with `;`

	#!/bin/sh
	
	TMPF=`tempfile`
	nyuu -C [config] [files] -o "$TMPF" -O && mv "$TMPF" ./output.nzb
	unlink "$TMPF" 2>/dev/null

**Comment by scriptzteam** [comment]
Thats was that thats for pointing me :) you are awesome!
