### ISSUE TITLE
Custom headers

### ISSUE THREAD

**Issue by shillshocked** [animetosho/Nyuu#33]
My news provider allows me to use custom headers. Is there some way you could implement this?

**Comment by animetosho** [comment]
Try the `--header` flag (see `nyuu --full-help` or *help.txt* for full details).

**Comment by shillshocked** [comment]
On a lark, I tried specifying this:

-H X-Complaints-To="The Three-ee Amigos"

And I got:
```
[ERR ] Unexpected fatal exception encountered, stack trace below
/home/destiny/bin/Nyuu-master/bin/nyuu.js:1086
		throw err; // this seems to change the exit code a bit :/
		^
```

**Comment by animetosho** [comment]
Unfortunately I'm unable to reproduce your issue.

Please provide further details:

* full command line
* full stack trace
* OS and Nyuu version

Thanks!

**Comment by shillshocked** [comment]
Using the latest version on Arch Linux, I can use this command successfully:

nyuu -C ~/bin/Nyuu-master/config.json -t "$dir" --out "$dir.nzb" -r include "$d"

where d is the directory basename, and dir is d without the trailing slash.

But when I add that line to produce:

nyuu -C ~/bin/Nyuu-master/config.json -H X-Complaints-To="The Three-ee Amigos" -t "$dir" --out "$dir.nzb" -r include "$d"

I get the error. Is this related to forced headers by the usenet provider?

I would send the stack trace but I'm currently processing a big upload, so perhaps latter.

**Comment by animetosho** [comment]
From the path name I'm assuming you're using the latest *Git* version (as opposed to release version).

Your config will be masking out a lot of the options, so unfortunately doesn't help by itself.

Ultimately the stack trace says where the problem is, so without it, I can't really do much.

Also, if you could provide info about when it occurs (e.g. soon after starting, takes a while, or just before it finished), that could help also.

Thank you!
