### ISSUE TITLE
Lot of missings article when posting

### ISSUE THREAD

**Issue by jhdscript** [animetosho/Nyuu#57]
Hello,

i m desesperate, all my posts failed because a lot of articles missing. I attached a screenshot

Args used are: -n10 -f "jhdscript <jhdscript@fakemail.com>" -k 1 -g alt.binaries.backup -o test2.nzb test

Fews uploads works good but after all failed with missings article :/

I try different article size but same issue. Maybe have you an idea ?

![sans titre](https://user-images.githubusercontent.com/6814361/53054133-b905f600-34a3-11e9-9886-fd8ea25ccca4.png)

**Comment by animetosho** [comment]
There's generally not too much you can do when a server just loses your posts. You can try increasing the number of retries (`--check-post-tries` option) I guess, maybe it'll work better. Sometimes I find that submitting the post again at some later time (say hours/days later) sometimes works.

If you want, you could try playing around with changing subjects, content etc to see if there's anything in particular which triggers your provider to just drop posts. Otherwise, it's really hard to know what the provider's doing as they don't often give details.

**Comment by jhdscript** [comment]
ok thanx animetosho. I need to upload 6Tb of data maybe you can advise me a good provider ?

**Comment by animetosho** [comment]
I do not provide such suggestions. Please keep questions related to Nyuu here.

**Comment by jhdscript** [comment]
Ok thanx for your support and for your code. Great job
