### ISSUE TITLE
Win10: Is there supposed to be an ETA displayed?

### ISSUE THREAD

**Issue by RollingStar** [animetosho/Nyuu#6]
https://github.com/animetosho/Nyuu/blob/4fdacda2c81cb79c2624f8ef6c33bb98f5cdab4b/bin/nyuu.js#L926

![image](https://cloud.githubusercontent.com/assets/4810902/19408125/b42b7098-9283-11e6-8da4-c994f8d65623.png)

On Windows 10 x64 Powershell, this is pretty much all you get. Is there supposed to be an estimated total upload time?

**Comment by animetosho** [comment]
I'm guessing you're using an older version - perhaps the one from the releases page?

If so, the feature was added after that. I'll need to update the pre-built package some time, as there's been a few changes since then.

You can always just grab the latest code by [downloading the ZIP package](https://github.com/animetosho/Nyuu/archive/master.zip) (or git cloning it). The pre-built package just includes `bin\\node.exe` `node_modules\\` and `nyuu.cmd` which you can just copy across.

**Comment by RollingStar** [comment]
Thanks!
