### ISSUE TITLE
Hi is it possible to fully automate nyuu? 

### ISSUE THREAD

**Issue by JavascriptHiFi** [animetosho/Nyuu#63]
is it possible to fully automate nyuu? the script is stack isn't cutting it it keeps messing up

ty

**Comment by animetosho** [comment]
Sorry, I don't really understand what you're exactly trying to say.

If you're having issues, please be specific about what the problem is.

**Comment by JavascriptHiFi** [comment]
Hello

I meant  if it's possible to make nyuu run indefinitely and keep posting automatically as a service  like nntpPoster

and thank you for your fast reply

**Comment by animetosho** [comment]
Nyuu isn't meant to run as a daemon. Depending on your exact use case, you might be able to set up a script to do what you want.  
For example, you could queue up commands using the [task-spooler](https://www.linux.com/news/queuing-tasks-batch-execution-task-spooler/) utility, if that's what you're looking for.

Otherwise, if nntpPoster gives you exactly what you want, I suggest just using that.
