### ISSUE TITLE
Upload speed fluctuates, but localhost reporting is accurate

### ISSUE THREAD

**Issue by RollingStar** [animetosho/Nyuu#7]
Relevant code:

https://github.com/animetosho/Nyuu/blob/4fdacda2c81cb79c2624f8ef6c33bb98f5cdab4b/bin/nyuu.js#L930

https://github.com/animetosho/Nyuu/blob/4fdacda2c81cb79c2624f8ef6c33bb98f5cdab4b/bin/nyuu.js#L978

My upload speed keeps flipping between 0, my upload speed, 2x my upload speed, and occasionally, 3x my upload speed. This affects the ETA calculation, I assume because somehow it's seeing a 0 KBps connection. The average speed reported on my connection for `--progress stderr --progress http:localhost:8888` is accurate: Raw Posting Upload Rate: 707.2 KiB/s.

I don't know if Nyuu is _inaccurately_ reporting my connection speed - it's possible my ISP is dropping connections in a weird way. But even if they are, the way Nyuu currently reports my speed isn't very useful. Is this an issue with only taking the last 4 seconds of upload speeds?

![output](https://cloud.githubusercontent.com/assets/4810902/19412093/2610b6f2-92dc-11e6-9ae5-588a6ee140de.gif)

**Comment by animetosho** [comment]
Do you have post checking enabled?

I suppose that the ETA can be calculated over a longer time window than the current speed indicator. This should handle speed fluctuations a bit better.  
As for the current speed, I'll need to think of a better way to indicate it. Your results point out something I hadn't really considered - since posts are typically around 700KB, if your upload rate is less than 700KB/s, the indicator will be constantly jumping around (and more so the slower the connection speed is).

The raw posting speed is calculated differently from the current speed indicator:
* it's based off overall progress, rather than the last 4 seconds
* it's based off data sent over the network, whilst the indicator in the console output is based off "progress". The distinction is particularly important in the case of failures, where it's actually possible for progress to go *backwards* (and hence result in negative speed) since posts have to be resubmitted.

Thanks for raising the issue!

**Comment by RollingStar** [comment]
Thanks for being so responsive. On top of that, Nyuu is one of the only Usenet uploaders I've found that actually works on my machine. And it's just about the only uploader made with modern principles.

In preliminary testing changing [this](https://github.com/animetosho/Nyuu/blob/4fdacda2c81cb79c2624f8ef6c33bb98f5cdab4b/bin/nyuu.js#L953) to more than 4 fixes the issue. I tried with 30 and will soon bring it down to 15 and see if it still works. The only side effect is I think it doesn't give an accurate speed / ETA while it's gathering the first batch of samples, because the first few seconds are 0 KBps before the upload begins.

I recommend just setting the number of samples higher if you don't want to spend more time on a more detailed fix to address sub-700 KBps speeds which would have the indicator constantly jumping around. Granted, I didn't write the program, and don't know if the sample count affects things besides the ETA and upload speed display.

>Do you have post checking enabled?

Does "connections: 0" disable it? And is this the default? This is the relevant section of my config.

```
/** Post Check Options **/
check: {
	// this 'server' block is identical to the 'server' block above
	// missing fields are simply copied from there
	server: {
		connect: {
		},
		connections: 0, // 1 is a good number, but if you're uploading fast enough that it becomes a bottleneck, increase it
	},
	delay: 5000, // (in ms) initial delay for performing check
	recheckDelay: 30000, // (in ms) delay retries by this amount of time; not used if tries<2
	tries: 3, // number of check attempts; should be 0 if not performing post checks
	group: '', // if set, will switch checking connections to this group; some servers seem to want one when STATing posts, otherwise they fail to show them; if set, should be a valid group you never post to, eg "bit.test"
	ulConnReuse: false, // use uploading connections for post checks; only works if checking the same server as the one being uploaded to
	postRetries: 1, // maximum number of post retry attempts after a post check failure; set to 0 to never retry posting
	queueBuffer: null, // maximum number of posts in the post-check queue; if this number is exceeded, uploading is paused until the queue is emptied below this size; default is numConnections*8
},
```

**Comment by animetosho** [comment]
Yes, increasing the window should fix the issue, at the expense of being less accurate in terms of "at the moment" speed (if it fluctuates). It shouldn't make a difference at the beginning, when there's few samples, though.

The problem is that, Nyuu sends whole articles at once - this is beneficial for limiting write calls (and hence overhead, on fast connections). However, it means that there's no way to determine current progress until at least one post has been successfully submitted, which is problematic on slower connections (since each post can take some time).  
I don't really intend to change this behaviour (Nyuu is primarily geared towards 1Gbps connections) but I can certainly make it less confusing.

Hopefully, the changes I've made so far satisfies all your concerns. The new code still uses the last 4 seconds, for faster connections, or the time taken to submit the last 4 posts, for slower connections. This should smooth out the speed indicator better. ETAs are calculated over a larger window.  
The one downside of this change is that upload stalls aren't immediately obvious, as the speed indicator will slowly go down rather than jump to 0.

> Does "connections: 0" disable it? And is this the default? This is the relevant section of my config.

Yes, it seems like post checking is disabled. I just wanted to confirm that there wasn't any possibility of check failures affecting the speed.

> On top of that, Nyuu is one of the only Usenet uploaders I've found that actually works on my machine. And it's just about the only uploader made with modern principles.

Thank you for the comment! Out of interest, if I may ask, what do you mean by 'modern principles'?

**Comment by RollingStar** [comment]
Thanks for the fix.

>Thank you for the comment! Out of interest, if I may ask, what do you mean by 'modern principles'?

jBinUp has a slow interface. Many other uploaders stopped development around 2002. SSL support is hard to come by, and they aren't really geared for big files. And quite a few just don't work, probably because they were never tested against OS's 4 iterations newer than the newest OS of the era (XP).

**Comment by animetosho** [comment]
Good to know it works, and thanks for your thoughts!
